package:
  name: suitcase
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - databroker
    - doct
    - event-model
    - h5py
    - jinja2
    - metadatastore
    - numpy
    - pandas
    - python
    - singledispatch  # [py2k]

test:
  imports:
    - suitcase
    - suitcase.spec
    - suitcase.hdf5

about:
  home: http://scikit-beam.github.io/scikit-beam/
  license: 3-Clause BSD
