package:
  name: suitcase
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../


build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - databroker
    - h5py
    - pandas

test:
  imports:
    - suitcase

about:
  home: http://scikit-beam.github.io/scikit-beam/
  license: 3-Clause BSD
